/* VISUALIZAR LA BASE DE DATOS DEL SERVIDOR*/

USE MASTER 
GO
SELECT * FROM sys.databases
GO

/*ELIMINAR BASE DE DATOS DE USUARIO */
DROP DATABASE BDnegocios
GO

DROP DATABASE BDnegocios2
GO
/*CREAR UNA BASE DE DATOS DE FORMA SIMPLE */

CREATE DATABASE BDNEGOCIOS
GO

/* VISUALIZAR LAS PROPIEDADES DE LA BD*/
EXEC sp_helpDB BDNEGOCIOS
GO

/* CREAR UNA BD CON OPCIONES PERSONALIZADAS*/

CREATE DATABASE BDNEGOCIOS1
ON
(
NAME=NEGOCIO1_DATA,
FILENAME='C:\DATA\NEGOCIO1_DATA.MDF',
SIZE=5MB,
MAXSIZE=50MB,
FILEGROWTH=3MB
)
LOG ON
(
NAME=NEGOCIO1_LOG,
FILENAME='C:\DATA\NEGOCIO1_LOG.LDF',
SIZE=10MB,
MAXSIZE=50MB,
FILEGROWTH=10MB
)
GO

EXEC SP_HELPDB BDNEGOCIOS1
GO

/* MODIFICAR EL TAMAÑO Y CRECIMINETO DEL DATAFILE POR LOS 
VALORES 10MB Y 5MB RESPECTIVAMENTE*/
ALTER DATABASE BDNEGOCIOS1
MODIFY FILE
(
NAME=NEGOCIO1_DATA,
SIZE=10MB,
FILEGROWTH=5MB
)
GO

/* MODIFICAR EL TAMAÑO MAXIMO DEL LOGFILE DE LA BD
Q SERA 200MB*/
ALTER DATABASE BDNEGOCIOS1
MODIFY FILE
(
NAME=NEGOCIO1_LOG,
MAXSIZE=200MB
)
GO

/*MODIFICAR LA BD PARA AGREGAR UN DATAFILE */
ALTER DATABASE BDNEGOCIOS1
ADD FILE
(
NAME=NEGOCIO1_DATAS1,
FILENAME='C:\NEGOCIO1_DATAS1.NDF'
)
GO

/*VER LA ESCRITURA */
EXEC SP_HELPDB BDNEGOCIOS1
GO

/*MODIFICAR LA BD PARA AGREGAR UN LOGFILE */
ALTER DATABASE BDNEGOCIOS1
ADD LOG FILE
(
NAME=NEGOCIO1_LOG2,
FILENAME='C:\DATA\NEGOCIO1_LOG2.LDF'
)
GO

--VER LA ESCRITURA

EXEC SP_HELPDB BDNEGOCIOS1
GO

/*ADJUNTAR BASE DE DATOS EN NUEVA UBICACION */
CREATE DATABASE BDNEGOCIOS1
ON
(FILENAME='C:/MYFOLDER\NEGOCIO1_DATA.MDF'),
(FILENAME='C:/MYFOLDER\NEGOCIO1_LOG.LDF'),
(FILENAME='C:/MYFOLDER\NEGOCIO1_LOG2.LDF')

FOR ATTACH
GO